### ISSUE TITLE
Setting to right prometheus server 

### ISSUE THREAD

**Issue by sojab0on** [msroest/sabnzbd_exporter#10]

**Comment by sojab0on** [comment]
How do i set the right prometuehes server in the docker command

**Comment by sojab0on** [comment]
Is it posible that a question is coming up to enter the api key and base url when tarting to py file for xport

**Comment by msroest** [comment]
The prometheus server isn't setup in the exporter the exporter is referenced in your prometheus server scrape configuration.

So you tell the exporter where your SAB install is via base url and api key. Then you setup you prometheus scrape to scrape the exporter once it's running with something like this:
```
- job_name: sabnzbd-exporter
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - <exporter machine name/ip>:9387
```
